name: Build and Deploy to test

on:
  push:
    branches:
      - test
      - test-pull-issues-from-here

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install

      - name: Lint code
        run: gem install rubocop && bundle exec rubocop

      - name: Scan for dependency vulnerabilities
        run: gem install bundler-audit && bundle exec bundler-audit update && bundle exec bundler-audit check

      - name: Run unit tests
        run: bundle exec rspec

    #   - name: Build Docker image
    #     run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ruby-app:develop .

    #   - name: Push Docker image
    #     run: |
    #       echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #       docker push ${{ secrets.DOCKER_USERNAME }}/ruby-app:develop